version: "3.7"

services:

  web:
    image: nginx:1.18
    ports:
      - 80:80
    volumes:
      - ./xenforo:/var/www/xenforo
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: images/php
    volumes:
      - ./xenforo:/var/www/xenforo
      - ./config/config.php:/var/www/xenforo/src/config.php

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: xenforo
